### ISSUE TITLE
If management URL is not correct, progress wheel spins indefinitely.

### ISSUE THREAD

**Issue by cwize1** [Azure/azure-digital-twins-graph-viewer#10]
Repro:
1. In the sign-in page, enter the management URL without a trailing forward-slash (/) character. For example, "https://<>.westus2.azuresmartspaces.net".
2. Fill in the rest of the sign-in details.
3, Hit 'Sign-in' button.

Expected: Graph is shown.
Actual: The progress wheel spins indefinitely. Also, the browser's debug console shows that there are failed HTTP requests.

**Comment by nielsams** [comment]
Hi
Thanks for reporting this. We'll make sure to add a check for this soon!
Cheers

**Comment by atatat123** [comment]
Hello,

After i login i get this progress wheel spinning.. But ive added the forward-slash.
Any idea's what could be wrong?

**Comment by rploeg** [comment]
@fernandoviton I have still the same issue with the spinning wheel. Any idea?

**Comment by fernandoviton** [comment]
@rploeg @arjantent: Have you looked at the browser debugger console window - that might provide some insight (I think the spinner just keeps going on basically any error).  If that doesn't have anything interesting then take a look at the network window and see what calls are failing.  Then post any findings here if that doesn't show you the problem and we can probably help more.

**Comment by rploeg** [comment]
@fernandoviton 

Other token error: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cc879146-9fca-43c9-b307-911f210d7d00
Correlation ID: 3e776c91-9950-4c3d-8a5b-3b60165d483a
Timestamp: 2019-08-26 10:00:41Z

Other applications that I have build on top of this ADT does work with the same authentication method
