### ISSUE TITLE
Step 6 of README, could be clearer that 'Edit Manifest' button is back on app page

### ISSUE THREAD

**Issue by ericloeliger** [Azure/azure-digital-twins-graph-viewer#11]
On step 6 of the README, it is not clear where the 'Edit Manifest' button is.  I was initially confused as I was not seeing it on the Settings and/or Settings/Required permissions blades.  Could be clearer to say return to the app blade.

**Comment by nielsams** [comment]
Thanks for the feedback. Will make sure to clarify that soon. 👍
