### ISSUE TITLE
Document well "Deploy Steps", they are too vague

### ISSUE THREAD

**Issue by alinamstanciu** [Azure/azure-digital-twins-graph-viewer#14]
Hi guys,

It took me a bit to deploy Graph Viewer and this is because of these steps being too generic. Could you please document these please? Do not assume your audience are devs ...

"Upload the files you've prepared in the previous step to your webserver. For example, you could create an Azure web app and deploy using FTP or VSTS. Alternatively, you could run this off a localhost webserver. Just make sure the reply-url in the AzureAD application has been set to the appropriate URL. Running this locally by opening the files is not supported, since the login redirect from AzureAD would fail."

Thank you
--Alina

**Comment by dnobel** [comment]
I added a PR how to build a docker container and run it as such. maybe that helps: https://github.com/Azure/azure-digital-twins-graph-viewer/pull/12

**Comment by nielsams** [comment]
@alinamstanciu we merged @dnobel s contribution to add a docker container. This makes it a lot more straightforward to deploy the graph viewer.
