### ISSUE TITLE
page not responding

### ISSUE THREAD

**Issue by yzll111** [Azure/azure-digital-twins-graph-viewer#16]
[
![1552920254238](https://user-images.githubusercontent.com/48660873/54538557-5dd4ff80-498c-11e9-92b8-3db798533e0c.jpg)
](url)

Hi there,

ive done all processes but blocked before logging into the site. 
when i put in my digital twin root url + tenant id + client id, there is no response from the site, 'sign in' icon does not work.

any help is appreciated.

**Comment by yzll111** [comment]
WEB: https://tomzstar.azurewebsites.net

**Comment by fernandoviton** [comment]
@yzll111: could this be related to #10?  (Can you check the url you put in has a trailing slash?)

**Comment by nielsams** [comment]
@yzll111 Did Fernando's suggestion solve the issue or are you still experiencing problems?
