### ISSUE TITLE
Spinning wheel

### ISSUE THREAD

**Issue by rploeg** [Azure/azure-digital-twins-graph-viewer#21]
Hi,

I am running the solution in a local docker container. I could sign in correctly, but after logging in, I see the screen but only with a spinning wheel. I have used the '/' on the end for my root URL. Any idea what can be wrong? 

thanks,

Remco

**Comment by nielsams** [comment]
Hi Remco
Is there anything useful on the javascript console?

**Comment by rploeg** [comment]
@nielsams  Sorry for the delays (holidays...)

Other token error: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cc879146-9fca-43c9-b307-911f210d7d00
Correlation ID: 3e776c91-9950-4c3d-8a5b-3b60165d483a
Timestamp: 2019-08-26 10:00:41Z

**Comment by madmaddy** [comment]
@rploeg @nielsams Any updates on this, please? Thank you

**Comment by nielsams** [comment]
@madmaddy are you seeing the same issue on the javascript console as above, or are you facing a different error?

**Comment by rploeg** [comment]
@madmaddy still same issue, think is the issue with my subscription or something (connected to hotmail account)

**Comment by madmaddy** [comment]
In my case, the issue was caused by the lack of role assignments. It wasn’t until i read another thread here that i realized that was missing. Many thanks for answering so quickly!
