### ISSUE TITLE
Trouble signing in

### ISSUE THREAD

**Issue by sanyam8182** [Azure/azure-digital-twins-graph-viewer#25]
I have deployed the code into a web app in azure but when i try to access the web app, it gives me the below error.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '1be*****************6d91475'.

the redirect url for the app service i have given is "https://twinsvisualizer.azurewebsites.net/"

**Comment by nielsams** [comment]
Hi @sanyam8182, 
the redirect URL you mention was part of the example. Please enter the URL of the web app you have deployed there.

**Comment by sanyam8182** [comment]
got it i had to give the name of my webApp instead of twinsvisualizer.
