### ISSUE TITLE
No view shown after login

### ISSUE THREAD

**Issue by ghost** [Azure/azure-digital-twins-graph-viewer#9]
HI - after following your deployment instructions I successfully logged into the graph viewer web app. All I am seeing is a spinning icon in the middle of the page? Can you please advise as to the cause?
![viewer1](https://user-images.githubusercontent.com/22078880/51614842-68d85a00-1f1e-11e9-942b-080503a044e2.gif)

**Comment by nielsams** [comment]
Hi Dave, Are there any useful messages on the javascript console?

**Comment by ghost** [comment]
ok good catch - forgot that. It says user or admin has not consented to the app ID. However, I am global admin in AAD and have selected Grant Permissions for the app. Not sure what else to do - not had this before?

**Comment by DoychinDoychev** [comment]
Any updates on that @nielsms? I'm having the same issue. It seems to be something with the AD, but i'm still new to az and have no idea how to fix it

**Comment by gabrielpereirapinheiro** [comment]
I'm having the same issue too, anyone knows how resolve that ?. @nielsms @DoychinDoychev @davebanthorpe

**Comment by nielsams** [comment]
@DoychinDoychev and @gabrielpereirapinheiro does your javascript console (F12) say anything useful on the matter?

**Comment by jamhamlee** [comment]
Same issue here, and my console shows

adal.min.js:2 

renewToken is failed:AADSTS65001: The user or administrator has not consented to use the application with ID '4aec841d-639f-4060-996a-0403a52826d2' named 'GraphViewer'. Send an interactive authorization request for this user and resource.
Trace ID: c05ad39a-ddf8-435e-b703-6c5c736c0b00
Correlation ID: 866c6f02-0652-4acd-8804-2a24a3d47489
Timestamp: 2019-02-27 06:45:30Z

------------------------------------------------------------------------------
login.js:84 
Other token error: AADSTS65001: The user or administrator has not consented to use the application with ID '4aec841d-639f-4060-996a-0403a52826d2' named 'GraphViewer'. Send an interactive authorization request for this user and resource.
Trace ID: c05ad39a-ddf8-435e-b703-6c5c736c0b00
Correlation ID: 866c6f02-0652-4acd-8804-2a24a3d47489
Timestamp: 2019-02-27 06:45:30Z

**Comment by nielsams** [comment]
Can you confirm that on your AD application, your 'Required Permissions' tab looks like this:
![image](https://user-images.githubusercontent.com/18422663/53473242-2e586480-3a6a-11e9-95bb-14b32a47fe1d.png)

And you clicked the 'grant permissions' button after adding the Digital Twins service to this screen?

**Comment by jamhamlee** [comment]
My screen shows
![snip_20190227160644](https://user-images.githubusercontent.com/14228886/53475013-c6297300-3aa9-11e9-8b31-175401f9837f.png)

After "Grant permissions", console showed "Succesfully retrieved token" (login.js:50).  
But other messages came.

![snip_20190227160019](https://user-images.githubusercontent.com/14228886/53474739-db51d200-3aa8-11e9-87cc-7673eb314d6d.png)

And I used this [provisionSample.yaml](https://github.com/Azure-Samples/digital-twins-samples-csharp/blob/master/occupancy-quickstart/src/actions/provisionSample.yaml) file as a sample.

**Comment by nielsams** [comment]
@jamhamlee  Can you add a '/' after your management url?

**Comment by jamhamlee** [comment]
Hooray. I add '/' after "Azure Digital Twins Instance Root Url" at first setting page. Then it works. 

Thank you, @nielsms.

**Comment by ghost** [comment]
Folks - sorry for delay replying (been off work).

For me the solution was just to use Edge browser. Chrome flat out failed -
soon as I switched to Edge it all worked fine.

-Dave

**Comment by nielsams** [comment]
@jamhamlee that's great news. We'll be sure to check for the / in a future release :)

Closing issue for now, let's re-open if clicking 'grant permissions' or adding / doesn't solve the problem

**Comment by xwdreamer** [comment]
chorme is not ok，Firefox and Safari is ok
